---
title: indigorescue.org
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: false
    social-share: false
- scope:
    path: ''
  values:
    layout: page
author: Indigo Rescue
navbar-links:
  About:
  - About Us: about
  - Our Programs: our-programs
  - Fundraising Board: fundraising_board
  - Staff & Board: staff_board
  - Events: events
  Adoption:
  - Adoptable Pets: adoptable-pets
  - Adoption Philosophy: adoption_philosophy
  - Adoption Policy: adoption_policy
  - Adoption Application: adoption_form_blocksurvey
  Volunteer or Foster:
  - Volunteer: volunteer
  - Foster: foster
  Donate: donate
  Contact: contact
avatar: "/assets/img/logo.png"
round-avatar: true
social-network-links:
  email: info@indigorescue.org
  facebook: indigorescue
  instagram: indigorescueanimals
  telephone: "(503) 626-7222"
share-links-active:
  twitter: false
  facebook: true
  linkedin: false
  vk: false
url-pretty: indigorescue.org
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
page-img: "/assets/images/background.jpg"
date_format: "%B %-d, %Y"
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
exclude:
- CHANGELOG.md
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- screenshot.png
- docs/
plugins:
- jekyll-paginate
- jekyll-sitemap
